version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/react_app/node_modules"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true # makes node's fs watchers play nice
      - GENESEARCH_URL=https://genesearch.kbase.us/ # URL for genesearch api
    stdin_open: true # Keeps start script alive
    command: sh scripts/start-dev.sh
